### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by istathar** [byteverse/chronos#75]
Would you be willing to have **chronos** added to Stackage? You've got a few packages in there so hopefully you'd be willing to see this added to the stable set as well. If you need help maintaining this library then we can certainly ask around for some volunteers if you want a hand.

Really appreciate the design of this library. Thanks for your thoughtful work.

**Comment by alaendle** [comment]
This package is present on stackage - so I guess this issue could be closed?
https://www.stackage.org/lts-22.23/package/chronos-1.1.6.1
