### ISSUE TITLE
Support ghc-9.10

### ISSUE THREAD

**Issue by alaendle** [byteverse/chronos#94]
Don't want to put pressure - just to have this in mind and maybe use as a reference 😃

**Comment by chessai** [comment]
> Don't want to put pressure - just to have this in mind and maybe use as a reference 😃 

Would take a PR

**Comment by chessai** [comment]
@alaendle the bytebuild PR was merged, if you want to PR here. just build with allow-newer locally and I'll do the relevant hackage updates.

**Comment by MangoIV** [comment]
Hi! I think all building blocks for cutting a release on both `bytebuild` and `chronos` are there - it would be nice if we could have it, if you have time, @chessai!

**Comment by chessai** [comment]
Done, 1.1.6.2 released
